// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boeyonezwmrbyeoayaqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZXlvbmV6d21yYnllb2F5YXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDg2MDUsImV4cCI6MjA3NDIyNDYwNX0.6jGyfuHeO7REceZMRz6BPEfUiauicWGocjWlRtvLEQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});